### ISSUE TITLE
Trouble using tar_to_tar.py to create RoBERTa*_IR_D

### ISSUE THREAD

**Issue by carlos-gemmell** [eladsegal/strategyqa#2] opened 2021-03-18 15:46 UTC
Hi,

I'm having a bit of trouble identifying the issue with tar_to_tar. I'm not terribly familiar with `.jsonnet` files and how they play in allenNLP so I might be missing something obvious.
It seems that the weights variable is not defined, which needs to be copied to the new tar.

I've been able to run, train, evaluate other models just fine, so al imports should be good.

Here is my terminal output:
```
root@pythonmlnotebookgpu2-1-7mlcz:/nfs/strategyqa# python3 tools/tar_to_tar.py pre-trained_models/5_STAR_IR-ORA-D/5_STAR_IR-ORA-D.tar.gz configs/strategy_qa/4_STAR_IR-D.jsonnet 4_STAR_IR-D.tar.gz
Extracting model...
Traceback (most recent call last):
  File "tools/tar_to_tar.py", line 34, in <module>
    main(args)
  File "tools/tar_to_tar.py", line 16, in main
    Params.from_file(args.config).to_file(os.path.join(tmpdirname, "config.json"))
  File "/usr/local/lib/python3.6/dist-packages/allennlp/common/params.py", line 488, in from_file
    file_dict = json.loads(evaluate_file(params_file, ext_vars=ext_vars))
RuntimeError: RUNTIME ERROR: undefined external variable: weights
        configs/strategy_qa/STAR_base.jsonnet:10:34-55  object <anonymous>
        configs/strategy_qa/STAR_base.jsonnet:(8:11)-(12:12)    thunk <array_element>
        configs/strategy_qa/STAR_base.jsonnet:(7:9)-(13:10)     thunk <array_element>
        configs/strategy_qa/STAR_base.jsonnet:(6:18)-(14:8)     object <anonymous>
        configs/strategy_qa/STAR_base.jsonnet:(5:20)-(15:6)     object <anonymous>
        configs/strategy_qa/STAR_base.jsonnet:(3:8)-(17:2)      object <anonymous>
        During manifestation
```

**Comment by eladsegal** [comment] 2021-03-19 00:23
Hi, the issue is fixed now.
Thank you!

**Closed as completed by eladsegal** 2021-03-19 00:23 UTC
